### ISSUE TITLE
Suggestion: allow `path` to optionally be an array.

### ISSUE THREAD

**Issue by abritinthebay** [devinivy/underdog#3]
It would be really nice to be able to do something like:

```
reply(content).push([
    somefile.js,
    someotherfile.css
]);
```

Rather than repeatedly doing `.push` calls. This would also allow easily setting the same headers for those resources (if required).

Thoughts? Criticisms? Reactions of pure unabated horror?

**Comment by devinivy** [comment]
I can see the value in that!  Would certainly take a PR for it.
